- name: Setup Cart Component
  hosts: all
  become: yes
  tasks:
    - name: Create Application User
      ansible.builtin.user:
        name: appuser
        system: yes
        shell: /bin/false
        create_home: no

    - name: Copy SystemD Service file
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: Install NodeJS
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Remove folder for application
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create folder for application
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download Application Content
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/cart.zip
        dest: /app
        remote_src: yes

    - name: Download App Dependencies
      ansible.builtin.shell: npm install --production
      args:
        chdir: /app

    - name: Apply permission for application folder
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        recurse: yes
        mode: 'o-rwx'

    - name: Start Service
      ansible.builtin.systemd_service:
        name: cart
        state: restarted
        enabled: yes
        daemon_reload: yes