- name: Setup MySQL component
  hosts: all
  become: yes
  tasks:
    - name: Install mysql8.4-server
      ansible.builtin.dnf:
        name: mysql8.4-server
        state: present

    - name: Restart service nginx, in all cases
      ansible.builtin.systemd_service:
        name: mysqld
        state: restarted
        enabled: yes

    - name: Setup NodeJS repo
      ansible.builtin.shell: |
        mysql -u root -e "
          CREATE USER 'root'@'%' IDENTIFIED BY 'RoboShop@1';
          GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
          ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';
          FLUSH PRIVILEGES;
        "