- name: Setup Shipping Component
  hosts: all
  become: yes
  tasks:
    - name: Create Application User
      ansible.builtin.user:
        name: appuser
        system: yes
        shell: /bin/false
        create_home: no

    - name: Copy SystemD Service file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: Install Java & Maven
      ansible.builtin.dnf:
        name:
          - java-21-openjdk
          - java-21-openjdk-devel
          - maven
        state: present

    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql8.4
        state: present

    - name: Remove folder for application
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create folder for application
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download Application Content
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/shipping.zip
        dest: /app
        remote_src: yes

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.rdevopsb89.online -u root -pRoboShop@1 < db/schema.sql
      args:
        chdir: /app

    - name: Load App User
      ansible.builtin.shell: mysql -h mysql-dev.rdevopsb89.online -u root -pRoboShop@1 < db/app-user.sql
      args:
        chdir: /app

    - name: Build Application Code
      ansible.builtin.shell: mvn clean package -DskipTests
      args:
        chdir: /app

    - name: Copy Jar file
      ansible.builtin.shell: cp target/shipping.jar /app/shipping.jar
      args:
        chdir: /app

    - name: Apply permission for application folder
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        recurse: yes
        mode: 'o-rwx'

    - name: Start Service
      ansible.builtin.systemd_service:
        name: shipping
        state: restarted
        enabled: yes
        daemon_reload: yes